# Generated by Django 2.2.13 on 2020-06-14 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0002_executerecord_execute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseexecuteresult',
            name='capture_screen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='caseexecuteresult',
            name='exception_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='belong_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autotest.ProjectInfo', verbose_name='所属项目'),
        ),
    ]
