# Generated by Django 2.2.13 on 2020-06-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0002_auto_20200620_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuiteinfo',
            name='cases',
            field=models.ManyToManyField(to='autotest.TestCaseInfo'),
        ),
    ]
