# Generated by Django 2.2.13 on 2020-06-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0003_testsuiteinfo_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuiteinfo',
            name='include_cases',
        ),
    ]
