# Generated by Django 2.2.1 on 2020-06-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0004_executerecord_execute_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executerecord',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='0：表示未执行，1：表示已执行'),
        ),
    ]
