# Generated by Django 2.2.1 on 2020-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0005_auto_20200601_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseexecuteresult',
            name='execute_time',
        ),
        migrations.AddField(
            model_name='caseexecuteresult',
            name='exception_info',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='caseexecuteresult',
            name='execute_end_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='执行结束时间'),
        ),
        migrations.AddField(
            model_name='caseexecuteresult',
            name='execute_start_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行开始时间'),
        ),
        migrations.AlterField(
            model_name='executerecord',
            name='status',
            field=models.IntegerField(help_text='0：表示未执行，1：表示已执行', null=True),
        ),
    ]
