# Generated by Django 2.2.1 on 2020-06-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0007_auto_20200601_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseexecuteresult',
            name='execute_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行结束时间'),
        ),
        migrations.AlterField(
            model_name='caseexecuteresult',
            name='execute_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行开始时间'),
        ),
    ]
