# Generated by Django 2.2.1 on 2020-06-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0008_auto_20200601_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseexecuteresult',
            name='capture_screen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='caseexecuteresult',
            name='exception_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='caseexecuteresult',
            name='execute_end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='执行结束时间'),
        ),
        migrations.AlterField(
            model_name='caseexecuteresult',
            name='execute_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='执行开始时间'),
        ),
    ]
