# Generated by Django 2.2.1 on 2020-06-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0011_auto_20200601_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseexecuteresult',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='执行结果'),
        ),
    ]
