# Generated by Django 2.2.1 on 2020-06-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0012_auto_20200603_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseexecuteresult',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
